export const contenido = [
    {
        classSection:"SeccionEncabezado",
        tipo: "ss",
        classTipo: "Encabezado",
        titulo: "DULCES DEL ALMA",
        classTitulo: "PosAbsolute Titulo",
        texto: "Los productos HUMAYA se elaboran desde hace más de 50 años con tradiciones familiares y sabores caseros, acompañándote en los momentos más importantes de tu vida.",
        classTexto: "PosAbsolute Texto1",
        texto2: "",
        classTexto2: "d-none",
        imagen: "https://i.postimg.cc/T25cXVCQ/imagen-Central2.jpg",
        classImage: "Image",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"ContentSection",
        tipo: "ss",
        classTipo: "Separador",
        titulo: "Manjares",
        classTitulo: "TituloSeparador",
        texto: "",
        classTexto: "d-none",
        texto2: "",
        classTexto2: "d-none",
        imagen: "#",
        classImage: "d-none",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"Class0",
        tipo: "card",
        classTipo: "Class1",
        titulo: "ALFAJORES DE DULCE DE LECHE TRADICIONALES",
        classTitulo: "Class2",
        texto: "Alfajores de maizena con relleno del mejor dulce de leche, con un borde de coco rayado.",
        classTexto: "Class3",
        texto2: "Cajas de 12 alfajores",
        classTexto2: "Class3",
        precio:"$500",
        classPrecio:"classPrecio",
        imagen: "https://i.postimg.cc/jSm9RxyJ/Producto1-Cuadrado.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
    {
        classSection:"Class0",
        tipo: "card",
        classTipo: "Class1",
        titulo: "DULCE DE LECHE TRADICIONAL",
        classTitulo: "Class2",
        texto: "Nuestro dulce de leche es un producto de excelente calidad y sobre todo excelente sabor.",
        classTexto: "Class3",
        texto2: "Unidades por 500gr",
        classTexto2: "Class3",
        precio:"$500",
        classPrecio:"classPrecio",
        imagen: "https://i.postimg.cc/R0tYFkTp/Producto2-Cuadrado.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
    {
        classSection:"Class0",
        tipo: "card",
        classTipo: "Class1",
        titulo: "TAPAS DE MAIZENA PARA RELLENAR",
        classTitulo: "Class2",
        texto: "Tapitas de maizena para rellenar en su hogar.",
        classTexto: "Class3",
        texto2: "Caja por 50 unidades.",
        classTexto2: "Class3",
        precio:"$500",
        classPrecio:"classPrecio",
        imagen: "https://i.postimg.cc/t4ZSSK8R/Producto3-Cuadrado.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
    {
        classSection:"Class0",
        tipo: "card",
        classTipo: "Class1",
        titulo: "Cupcakes Super Cremosos",
        classTitulo: "Class2",
        texto: "Enamorate de todos nuestros Cupcake y mini Cupcake #Crujientes y #Extrahumedos a mitad de precio",
        classTexto: "Class3",
        texto2: "Promoción Combo Especial",
        classTexto2: "Class3",
        precio:"$500",
        classPrecio:"classPrecio",
        imagen: "https://i.postimg.cc/xjRjsL9p/Producto-Prinicipal.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
    {
        classSection:"Class0",
        tipo: "ss",
        classTipo: "Class1 text-white",
        titulo: "ALFAJORES DE MAICENA",
        classTitulo: "Class2",
        texto: "Alfajores de dulce con coco rallado, relleno con 2cm de pura dulzura.Pudiendo elegir entre dulce de leche tradicional, light o choconutt.",
        classTexto: "Class3",
        texto2: "Presentación en caja de 6 y 12 alfajores.",
        classTexto2: "Class5",
        imagen: "https://i.postimg.cc/BnrhdhGT/Producto-Destacado-Desktop.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5"
    },
    {
        classSection:"Class0",
        tipo: "ss",
        classTipo: "Class1 text-white",
        titulo: "La mejor calidad solo para vos",
        classTitulo: "Class2",
        imagen: "https://i.postimg.cc/gkBtKzSB/Calidad.png",
        classImage: "Class4",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"Class0",
        tipo: "ss",
        classTipo: "Separador",
        titulo: "contacto",
        classTitulo: "TituloSeparador",
        imagen: "#",
        classImage: "d-none",
        boton: "",
        classBoton: "d-none"
    },

];
