export const contenido = [
    {
        classSection:"SeccionEncabezado",
        tipo: "ss",
        classTipo: "Encabezado",
        titulo: "DULCES DEL ALMA",
        classTitulo: "Titulo",
        texto: "Los productos HUMAYA se elaboran desde hace más de 50 años con tradiciones familiares y sabores caseros, acompañándote en los momentos más importantes de tu vida.",
        classTexto: "Texto1",
        texto2: "",
        classTexto2: "d-none",
        imagen: "https://i.postimg.cc/T25cXVCQ/imagen-Central2.jpg",
        classImage: "Image",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"SeccionSeparador",
        tipo: "ss",
        classTipo: "Separador",
        titulo: "Manjares",
        classTitulo: "TituloSeparador",
        texto: "",
        classTexto: "d-none",
        texto2: "",
        classTexto2: "d-none",
        imagen: "#",
        classImage: "d-none",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"SeccionCard",
        tipo: "card",
        classTipo: "Carta",
        titulo: "ALFAJORES DE DULCE DE LECHE TRADICIONALES",
        classTitulo: "TituloCard",
        texto: "Alfajores de maizena con relleno del mejor dulce de leche, con un borde de coco rayado.",
        classTexto: "TextoCard1",
        texto2: "Cajas de 12 alfajores",
        classTexto2: "TextoCard2",
        precio:"$500",
        classPrecio:"PrecioCard",
        imagen: "https://i.postimg.cc/jSm9RxyJ/Producto1-Cuadrado.png",
        classImage: "ImageCarta",
        boton: "agregar al carrito",
        classBoton: "btnCard",
        classBody: "BodyCard",
    },
    {
        classSection:"SeccionCard",
        tipo: "card",
        classTipo: "CartaInverter",
        titulo: "DULCE DE LECHE TRADICIONAL",
        classTitulo: "TituloCard",
        texto: "Nuestro dulce de leche es un producto de excelente calidad y sobre todo excelente sabor.",
        classTexto: "TextoCard1",
        texto2: "Unidades por 500gr",
        classTexto2: "TextoCard2",
        precio:"$500",
        classPrecio:"PrecioCard",
        imagen: "https://i.postimg.cc/R0tYFkTp/Producto2-Cuadrado.png",
        classImage: "ImageCarta",
        boton: "agregar al carrito",
        classBoton: "btnCard",
        classBody: "BodyCard",
    },
    {
        classSection:"SeccionCard",
        tipo: "card",
        classTipo: "Carta",
        titulo: "TAPAS DE MAIZENA PARA RELLENAR",
        classTitulo: "TituloCard",
        texto: "Tapitas de maizena para rellenar en su hogar.",
        classTexto: "TextoCard1",
        texto2: "Caja por 50 unidades.",
        classTexto2: "TextoCard2",
        precio:"$500",
        classPrecio:"PrecioCard",
        imagen: "https://i.postimg.cc/t4ZSSK8R/Producto3-Cuadrado.png",
        classImage: "ImageCarta",
        boton: "agregar al carrito",
        classBoton: "btnCard",
        classBody: "BodyCard",
    },
    {
        classSection:"SeccionCard posRelative",
        tipo: "card",
        classTipo: "Carta CartaPromo",
        titulo: "Promoción Combo Especial",
        classTitulo: "TextoCard1",
        texto: "Cupcakes Super Cremosos",
        classTexto: "TituloCard",
        texto2: "Enamorate de todos nuestros Cupcake y mini Cupcake #Crujientes y #Extrahumedos a mitad de precio",
        classTexto2: "TextoCard1",
        precio:"$500",
        classPrecio:"PrecioCard",
        imagen: "https://i.postimg.cc/xjRjsL9p/Producto-Prinicipal.png",
        classImage: "ImageCartaPromo",
        boton: "agregar al carrito",
        classBoton: "btnCard",
        classBody: "BodyCardPromo",
    },
    {
        classSection:"SeccionCard",
        tipo: "card",
        classTipo: "CartaInverter",
        titulo: "ALFAJORES DE MAICENA",
        classTitulo: "TituloCard",
        texto: "Alfajores de dulce con coco rallado, relleno con 2cm de pura dulzura.Pudiendo elegir entre dulce de leche tradicional, light o choconutt.",
        classTexto: "TextoCar1",
        texto2: "Presentación en caja de 6 y 12 alfajores.",
        classTexto2: "TextoCard2",
        precio:"$500",
        classPrecio:"PrecioCard",
        imagen: "https://i.postimg.cc/BnrhdhGT/Producto-Destacado-Desktop.png",
        classImage: "ImageCarta",
        boton: "agregar al carrito",
        classBoton: "btnCard",
        classBody: "BodyCard",
    },
    {
        classSection:"SeccionCalidad",
        tipo: "ss",
        classTipo: "text-white",
        titulo: "La mejor calidad solo para vos",
        classTitulo: "text-white",
        imagen: "https://i.postimg.cc/gkBtKzSB/Calidad.png",
        classImage: "Class4",
        boton: "",
        classBoton: "d-none"
    },
    {
        classSection:"Class0",
        tipo: "ss",
        classTipo: "Separador",
        titulo: "contacto",
        classTitulo: "TituloSeparador",
        imagen: "#",
        classImage: "d-none",
        boton: "",
        classBoton: "d-none"
    },

];
