export const contenido = [
    {
        tipo: "card",
        classTipo: "Class1",
        titulo: "Nombre de producto 1",
        classTitulo: "Class2",
        texto: "Descripcion del producto asd123",
        classTexto: "Class3",
        imagen: "https://i.postimg.cc/jSm9RxyJ/Producto1-Cuadrado.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
    {
        tipo: "ss",
        classTipo: "Class1 text-white",
        titulo: "Nombre de producto 2",
        classTitulo: "Class2",
        texto: "Otras descripcion del producto asd456",
        classTexto: "Class3",
        imagen: "https://i.postimg.cc/SNZ3t7sd/carousell-conito-Cuadrada.png",
        classImage: "Class4",
    },
    {
        tipo: "ss",
        classTipo: "Class1 text-white",
        titulo: "Nombre de producto 3",
        classTitulo: "Class2",
        texto: "Otras descripcion del producto asd789",
        classTexto: "Class3",
        imagen: "https://i.postimg.cc/R0tYFkTp/Producto2-Cuadrado.png",
        classImage: "Class4",
    },
    {
        tipo: "card",
        classTipo: "Class1",
        titulo: "Nombre de producto 4",
        classTitulo: "Class2",
        texto: "Descripcion del producto qwe123",
        classTexto: "Class3",
        imagen: "https://i.postimg.cc/jSm9RxyJ/Producto1-Cuadrado.png",
        classImage: "Class4",
        boton: "agregar al carrito",
        classBoton: "Class5",
        classBody: "classBody",
    },
];
